### ISSUE TITLE
Currency not displayed at the instance configuration form

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_authorizedotnet#1]
When adding an instance of the enrolment plugin into the course, the site-wide configured currency is not displayed. So the teacher does not know what currency applies.

**Comment by parthajeet** [comment]
Hello David,

Thanks for the feedback. We will fix the mentioned issue and re-upload the plugin by today.

Thanks  and Regards,
parthaJeet~

**Comment by parthajeet** [comment]
We have fixed the mentioned issue. Please let us know if any further changes are needed or not.

Thanks,
parthaJeet~
