### ISSUE TITLE
Authorize.net plugin enrollment not enrolling

### ISSUE THREAD

**Issue by dwyvill** [dualcube/moodle-enrol_authorizedotnet#11]
Just had authorize.net moodle plugin installed. It is allowing the transaction and payment is being processed, but the student is enrolled with the same start and end date, so they cannot access the course. Verified that the default enrollment time is 365 days and that the Course End Date is not enabled. 
![screen shot 2018-09-11 at 1 05 21 pm](https://user-images.githubusercontent.com/43185373/45382685-39a3fa80-b5c6-11e8-82d0-e92b388bf723.png)

Has anyone else seen this? Any ideas on how to resolve?

**Comment by parthajeet** [comment]
Dear Dwyvill,

Thanks for your comment. Please ensure that you have entered a valid number in the enrolment duration field and check the box. 

Apart from that if you do not want to use the start date and end date, do not check the boxes i.e
![screenshot from 2018-09-14 11-16-39](https://user-images.githubusercontent.com/8317605/45532285-1e78fb00-b811-11e8-9d0e-99eefc25b135.png)
 enable them.

If you do want to use it, please make sure that the start date and end date are different and check the boxes.

Thank you.

**Comment by parthajeet** [comment]
Dear Dwyvill,

Can you please let me know the Moodle version that you are using?
Actually, this is the first time such an issue is reported. We would do everything to help you out.

Thank you.

**Comment by dwyvill** [comment]
We are on Moodle version 3.4.  Thanks!

**Comment by CtanShard** [comment]
@parthajeet Hello;  I am working with Dwyvill on this issue.  Is there anything I can provide that will assist with the diagnosis of this issue?.  I can set up screen sessions or set an account for you to view the issue if that will help.  Thanks for your time

**Comment by parthajeet** [comment]
@CtanShard 
Hi! Please create a staging for me using a sandbox so that I can test it.
Please share an admin and student credentials.

Thank you.

**Comment by CtanShard** [comment]
@parthajeet Thanks for getting back to me.  Do you need any sort of back end access for this testing?.  The environment we are working in is not yet live so if you are able to test with just some Moodle accounts I can set you up in the environment we are already running.

**Comment by CtanShard** [comment]
@parthajeet In case there is still anything that you can do for this issue;  The instance details are as follows:

This is a clean install of Moodle 3.4.4 running the latest available version of the authorize.net plugin.  The plugin currently applies an identical value in the start and end enrollment date making it impossible for the student to enter the class after paying.  We have had to disable enrollment dates to work around the issue.

Thanks for any and all of your time.

**Comment by jstilwell** [comment]
Hello,

We're experiencing exactly this same issue on our Moodle 3.5 site. The transaction is successful and the user is enrolled, but their status is listed as not current even though the enrollment duration is set to 120.

**Comment by parthajeet** [comment]
Hi!!
We tried to reproduce the issue on a fresh Moodle 3.5 but could not.

We are looking into it and hope to solve it as soon as possible after we find it.
Thank you.

**Comment by jstilwell** [comment]
@parthajeet Good morning. I just wanted to check back in to see if there was any way I could help with tracking this issue down? It's the only thing holding us back from using the plugin.

**Comment by parthajeet** [comment]
@jstilwell  To view the enrolment duration you have to add some settings in authorize.net plugin,
Go to course administration (in which the authorize.net is enabled)-> users-> Enrolment Methods->Authorize.net-> give the custom name,allow enrolments, give enrolment cost, -> Enable the enrolment duration(put the no. of days/month/year) ->Enable start date->Enable end date ( put the end date which is greater than start date).->click save changes.

After enrolments, an admin can view the enrolment duration by following steps.

Go to course administration (in which the authorize.net is enabled)-> users->enrolled user(here you can see the enrolment duration of the currently enrolled user.

Thank you.

**Comment by parthajeet** [comment]
Dear CtanShard,
@CtanShard 
Please share the admin access credentials and FTP credentials or create a staging for us so that we can at least check the issue.

We could not produce the issue on our server. Thank you.
