### ISSUE TITLE
Authorize.Net 'relay response' changes approaching, end of MD5 hash

### ISSUE THREAD

**Issue by goose2000** [dualcube/moodle-enrol_authorizedotnet#12]
I want to enter this as a support request. I imagine folks/maintainers are becoming aware of the change:

Authorize.Net is phasing out the MD5 based hash use for transaction response verification in favor of the SHA-512 based hash utilizing a Signature Key.  If your existing integrations or clients are using MD5 hash, they will need to move to using the SHA-512 based hash.  This applies to all Authorize.Net integration methods including the Authorize.Net API, AIM, SIM/DPM and Relay Response.

And some example:
https://developer.authorize.net/support/hash_upgrade/

**Comment by parthajeet** [comment]
We have upgraded the plugin. Thank you.

**Comment by goose2000** [comment]
Thank you so much! Will test as soon as it's feasible / possible

**Comment by nileshnpathade** [comment]
Showing me Warning.
Warning: hex2bin(): Hexadecimal input string must have an even length in....

Please look into this

**Comment by parthajeet** [comment]
Can you please check now.

**Comment by nileshnpathade** [comment]
Issue solved 
Thank you Parthajeet

**Comment by parthajeet** [comment]
Thank you Nilesh.

**Comment by nileshnpathade** [comment]
It's a really great support. Thank you, guys.

But still, I am facing the issue as following.
The following errors have occurred.
(99) This transaction cannot be accepted.

I have update Signature key which is a new update from the authorized dot net plugin. ( 7th Feb 2019 updates)

Moodle Version 3.5

I have tried https://developer.authorize.net/api/reference/responseCode99.html 

to get the response and it's showing me the process of update transaction key and I have followed it and update also transaction key. Still, I am facing the same issue

**Comment by parthajeet** [comment]
Hi! Nilesh,
Can you please update it again and let us know. Because we have tested it multiple times after you reported and everything is working good.

Thank you.

**Comment by nileshnpathade** [comment]
Could you please test on  Moodle 3.3. It's not working for me.

I have change transaction key and the signature key couple of time. still not working.

**Comment by parthajeet** [comment]
Hello,

We tested in Moodle 3.3 and its working correctly. Make sure you update the Authorize.net merchant Signature key and then add it in the Moodle site.

**Comment by nileshnpathade** [comment]
Yes, I have updated the authorize.net merchant signature key and added in Moodle site.

Is there any case issue.greated key showing UPPER CASE? 
Or any other issue. Please assist me.

**Comment by parthajeet** [comment]
No case is not an issue. Can you provide us with your site admin access and ftp details so that we can check once?

**Comment by nileshnpathade** [comment]
Hi Parthajeet, 
I am so sorry I can't provide access to you. 

Apart from the Transaction key and signature key, there is any other setting or any other parameters which, we are sending from hidden fields by clicking buy now button form.

I have change transaction key and signature key number of times. So is there need to wait some time to make it active these key?

I have disabled Old Signature Key and transaction Key Immediately by clicking the checkbox.

![screenshot from 2019-02-11 17-19-51](https://user-images.githubusercontent.com/13468332/52561409-59fc0d80-2e21-11e9-9083-c9cf76adc4bf.png)

**Comment by parthajeet** [comment]
Everything seems to be fine. Are doing a live transaction or test transaction?

**Comment by nileshnpathade** [comment]
Yes It's live

**Comment by parthajeet** [comment]
Can you try in test mode and let us know if its working or not?

**Comment by nileshnpathade** [comment]
Hi Parthajeet,

I have created a sandbox account and create transaction and signature key, which I have put into the test server. and it may work and after payment, it showing me the following message.

**_The reporting of this transaction to the Merchant has timed out. An e-mail has been sent to the merchant informing them of the error. The following is the result of the attempt to charge your credit card. 

      This transaction has been approved.
It is advisable for you to contact the merchant to verify that you will receive the product or service._**

Same plugin which I am using in live the server and live keys but it's after clicking on Buy now then it's showing me (99) error.

**Comment by parthajeet** [comment]
Can you once contact with Authorize.net regarding this error. As the transaction is getting approved. So what should be the next step.
