### ISSUE TITLE
Fingerprint Missing Currency Code

### ISSUE THREAD

**Issue by SamMcCullough** [dualcube/moodle-enrol_authorizedotnet#13]
Hello,

I have been troubleshooting an Error 99 code issue for the past day. After finding the Authorize.net [SIM API Guide PDF](https://www.authorize.net/content/dam/authorize/documents/SIM_guide.pdf), I was able to trace my problem to the SHA-512 Finger not containing the currency parameter. After adding in the currency, I was able to authenticate against my Authorize.net and make a purchase/enrolment. 

The update I made was to line 53 of enrolment_form.php.

Current Code 
`$fingerprint = hash_hmac("sha512", $loginid . "^" . $sequence . "^" . $timestamp . "^" . $amount . "^", $sigkey);`

My Change
`$fingerprint = hash_hmac("sha512", $loginid . "^" . $sequence . "^" . $timestamp . "^" . $amount . "^" . $instance->currency, $sigkey);`

Apologize, I am not really a developer and do not usually use Git. I'm not sure if this change is required globally for all users of this plugin. But it has helped me to resolve my problem.

Thank you,
Sam McCullough

**Comment by goose2000** [comment]
@SamMcCullough  - thanks for sharing that! - going through some site updates and getting ready to make the switch to this new version.

**Comment by Mihailoff** [comment]
Made a PR

**Comment by parthajeet** [comment]
Thanks, patch merged.

**Comment by goose2000** [comment]
I just will add I have the the new plugin running live. But when I upgraded through the Moodle plugins page, it pulled a package that did not contain this fix. I then pulled from Git and over wrote the directory, tested and seemed to process normal.

So, the Moodle distribution may need an update still - thank you guys.

**Comment by parthajeet** [comment]
Update.
