### ISSUE TITLE
Error(Exception - Call to a member function enrol_user() on null is there error)

### ISSUE THREAD

**Issue by marcomarino2017** [dualcube/moodle-enrol_authorizedotnet#18]
I check the previous issue about this one in [https://github.com/dualcube/moodle-enrol_authorizedotnet/issues/15](url)
But looks like there is not solution.

**Comment by 10101010101010001** [comment]
Currently the only solution is to use a different version of Moodle. Moodle 3.7.9 is reported to be working with Release 2.5 (Build: 20150610).  This is a duplicate issue.

**Comment by marcomarino2017** [comment]
I did upgrade to Moodle 3.7.9 and still have issues Invalid authorization etc.
Everything is correct such as API login and Trans. Key and machine client.

**Comment by marcomarino2017** [comment]
![image](https://user-images.githubusercontent.com/25055242/109342337-b7f9c300-7839-11eb-8549-281606fbc73a.png)

**Comment by marcomarino2017** [comment]
![image](https://user-images.githubusercontent.com/25055242/109342461-e24b8080-7839-11eb-8596-f5695a600949.png)

**Comment by marcomarino2017** [comment]
![image](https://user-images.githubusercontent.com/25055242/109342529-fee7b880-7839-11eb-9317-6efb7c9e56b3.png)

**Comment by marcomarino2017** [comment]
![image](https://user-images.githubusercontent.com/25055242/109342595-16bf3c80-783a-11eb-9105-b5bac8418ef6.png)

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
