### ISSUE TITLE
enrol_paypal not listed as explicit dependency

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_authorizedotnet#2]
Even if it is distributed as part of the core, the dependency on enrol_paypal should be explicitly declared in your version.php

However, I am wondering whether you actually need it? Surely the `get_string('enrolenddaterror', 'enrol_paypal');` should better be copied as a new string to your plugin. Where else is the paypal enrolment needed? (i.e. why is it required in your return.php file?)

**Comment by parthajeet** [comment]
Hello David,

Thanks for the feedback. We will fix the mentioned issue and re-upload the plugin.

Thanks and Regards,
parthaJeet~

**Comment by parthajeet** [comment]
Actually there is no such dependencies on Paypal for this plugin. We were following the code structure from the paypal enrollment, already provided by moodle. The get_string('enrolenddaterror', 'enrol_paypal'); was left in our code. Now we have replaced the code.

Thanks,
parthaJeet~
