### ISSUE TITLE
User authentication failed due to invalid authentication values.

### ISSUE THREAD

**Issue by marcomarino2017** [dualcube/moodle-enrol_authorizedotnet#20]
I replaced in pay_process.php to production link which is $url="https://api.authorize.net/xml/v1/request.api";
and i have new transaction key and API login ID and public key and i reset these 2 times till now, and i still getting this error User authentication failed due to invalid authentication values. is there any solution please.
![image](https://user-images.githubusercontent.com/25055242/110828060-aadeca00-8264-11eb-96c6-bf4d600abb4f.png)

**Comment by mailforsachin** [comment]
Hello, I cannot get out of this error. Can you suggest what else must be done to fix this?

**Comment by kundandualcube** [comment]
it's solved and added in the latest version
