### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by SactoBob** [dualcube/moodle-enrol_authorizedotnet#28]
Using cPanel, the zip file uploads using the plugin install file upload (no error there) and shows in the selection window. I've also checked in the moodledata directory and there several folders now with the "plugin.zip" file there so it made it to the server. However, when clicking on Install this comes up:

Install plugin from ZIP file
Validating enrol_authorizedotnet ... Error
  [Error] Extracted file not found [{"file":"authorizedotnet\/.git\/refs\/tags\/"}] 
Installation aborted due to validation failure

Any ideas? I've installed other plugins successfully before this one.

**Comment by SactoBob** [comment]
Also unable to install via the moodle plugin method:

There is a request to install plugin Authorize.net (enrol_authorizedotnet) version 2022050601 from the Moodle plugins directory on this site. However, the plugin installation pre-check failed (reason code: remoteunavailable).

**Comment by moumitahalder** [comment]
@SactoBob, we have released an update.

Kindly check now.

**Comment by SactoBob** [comment]
Thanks for the quick response! Verified, installation works again.

enrol_authorizedotnet
Success

Much appreciated!

-Bob
