### ISSUE TITLE
Is it good idea to ask people to fill their card number in Moodle form?

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_authorizedotnet#3]
Many people refuse, for good reasons, to fill their card number credentials to other sites than to trusted payment portals themselves (with all the HTTPS and additional protection). Does Authorize.net provide a way so that you would only display the button to proceed to the payment gate without actually submitting the card number?

**Comment by mudrd8mz** [comment]
Something like http://developer.authorize.net/api/simplecheckout/ maybe?

**Comment by parthajeet** [comment]
Hello David,

Actually we have used AIM method to integrate the Authorize.net payment. 

Link - http://developer.authorize.net/api/aim/

Kindly suggest whether we should replace it with the simplecheckout method.

Thanks,
parthaJeet~

**Comment by mudrd8mz** [comment]
I see, thanks for the info. Well, I'm really not in the position to judge over your decision to use this API. I was just sharing my worries that when it comes to payments, people should pay attention to what page they submit their credit card numbers. There is no point of the AIM security if at the end, people will use your plugin at HTTP Moodle sites. That is why, if it was me, I would personally prefer keeping things as simple as possible, off-loading as much as possible to the trusted payment gateways.

**Comment by parthajeet** [comment]
Hello David,

Thanks a lot for the feedback. Yes that's correct people prefer trusted payment gateway interface. Sure we will do the necessary changes and notify you.

Thanks,
parthaJeet~

**Comment by parthajeet** [comment]
Hello David,

We have updated our plugin in github as per the necessary changes mentioned. Should we upload in Moodle.org for re-approval?

Kindly suggest.

Thanks and Regards,
parthaJeet~
