### ISSUE TITLE
What API does your plugin use?

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_authorizedotnet#4]
I have not found a clear docs on what of the [available APIs](http://developer.authorize.net/api/) you plugins uses. When it comes to payments, these things should be clear.

**Comment by parthajeet** [comment]
Sure we will update in the documentation.

Thanks,
parthaJeet~

**Comment by parthajeet** [comment]
Hello David,

We have updated our plugin in github as per the necessary changes mentioned. Should we upload in Moodle.org for re-approval?

Kindly suggest.

Thanks and Regards,
parthaJeet~
