### ISSUE TITLE
Plugin does not check the payment was really done and the callback is valid

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_authorizedotnet#5]
Right, so your `ipn.php` blindly accepts any POST request that _looks_ like coming from the payment gateway and enrols the user. There must be some call back to the payment gateway to check that the payment was really done. Otherwise, any user can simply mimic the gateway response and let them be enrolled into the course (I just tried it on my local machine and I was able to bypass the payment completely as a student).

**Comment by parthajeet** [comment]
Hello David,

Authorized.net do provide a callback method to retrieve transaction details but unfortunately it does not work in sandbox mode.

http://developer.authorize.net/api/transaction_details/

We have used the MD5 Hash Security feature to authenticate the payment transaction(updated in github).

http://developer.authorize.net/faqs/#md5

https://support.authorize.net/authkb/index?page=content&id=A588

Please suggest if any modification is needed or should we request for a re-approval.


Thanks and regards,
parthaJeet~

**Comment by mudrd8mz** [comment]
When checking for the hash

    if ($generatemd5hash != $responsearray['x_MD5_Hash']) {

maybe you could use the `!==` operator to avoid accidental false positive check due to PHP implicit type checking.
