### ISSUE TITLE
Plugin does not work in production mode

### ISSUE THREAD

**Issue by sabuson** [dualcube/moodle-enrol_authorizedotnet#6]
Plugin uses testmode, so that student is enrolled without any actual payment.
testmode is hardcoded in line 31 of enrolment_form.php.
$testmode = "true";
May be this should be overriden when "check for production" mode option is "checked".

**Comment by parthajeet** [comment]
Thanks, we have removed the hard code.

**Comment by sabuson** [comment]
Thanks Parthajeet
