### ISSUE TITLE
An unanticipated error occurred while processing this request. 

### ISSUE THREAD

**Issue by adamz01h** [dualcube/moodle-enrol_authorizedotnet#7]
When using a sandbox account running a test transaction , works, payment is submitted, however I am stuck after everything goes through with a screen that says
"
Error
An unanticipated error occurred while processing this request. Please click your browserâ€™s Back button to return to the previous page.
" 
https://test.authorize.net/gateway/transact.dll is the url

**Comment by parthajeet** [comment]
Hello,

This is error generated when sandbox account is down. We request you to try after sometime. For live transactions you will not face such problem.

For better reference you may view this link:- https://community.developer.authorize.net/t5/Integration-and-Testing/Sandbox-environment-is-down/td-p/39533

Thanks,
Parthajeet~
