### ISSUE TITLE
User does not enroll properly

### ISSUE THREAD

**Issue by nevoband** [dualcube/moodle-enrol_authorizedotnet#8]
Hi,

For some reason when students use the authorize.net plugin to enroll into a course they can see the topic title but not its contents in the course.
I've tested the course with the self enrolment plugin and it's functioning correctly.
This is happening to all of my courses so it's not a specific issue to my course.

Have you seen this issue before?

Thank you

**Comment by nevoband** [comment]
Submitted a pull request for this in case this is happening to anyone else

**Comment by parthajeet** [comment]
Hello, 

We have checked again but haven't face such issue. Thanks for the feedback. We will check and update the plugin if needed.

Regards
